### ISSUE TITLE
[BUG] [1.7.0.2] nvidia rig mines ethereum and lyra2rev2 at the same time

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#206]
NHM shows lyra2re as currently being mined though both ccminer and ethminer are open

ethminer often restarts in this case, but there are always two miners open

log appended below

[log.txt](https://github.com/nicehash/NiceHashMiner/files/457638/log.txt)

**Comment by nicehashdev** [comment]
Is ethereum just open or is actually mining? It is normal that ethereum is open (idle), because it is keeping DAG file in memory, so it does not have to be regenerated when mining is switched to ethereum.

**Comment by felixbrucker** [comment]
this is being displayed, i assume it is trying to mine but is not allowed to connect (or something)
![unbenannt](https://cloud.githubusercontent.com/assets/5189997/18290088/62d39e10-7482-11e6-819e-c6925db0d738.PNG)

**Comment by nicehashdev** [comment]
No, that is fine then; if last lines of ethminer are "disconnecting" and "stopping farm", then ethminer is being put on pause and would resume later.

A bug would be there, if ethminer and ccminer would actually mine at the same time. Did you notice anything like that? In that case, both would mine with reduced speed.

**Comment by felixbrucker** [comment]
i noticed the rig being connected to both algos (will provide a similar screen for this if i encounter it again) and the ethminer cmd actually outputted some text while ccminer was running

maybe it was just the moment it switched

**Comment by felixbrucker** [comment]
now it switched back to the ethminer (because it is more profitable) and just lagged 3 minutes till it started mining

cpu usage of ethminer was 99% during this time, output was just garbled text

![unbenannt](https://cloud.githubusercontent.com/assets/5189997/18290926/bccedb2a-7485-11e6-919e-cb07e706d0a7.PNG)

it seems faster to just regenerate the dag

**Comment by S74nk0** [comment]
Hi @felixbrucker. Ethminer CPU load is definitely too high. Try increasing Miner Restart Delay ms(MinerRestartDelayMS) to 1000,2000 (1 or 2 seconds) in Settings Advanced tab. If that does not help, try changing Dag Load Mode from singlekeep to parallel (also Settings Advanced tab). Please report back if this has helped.

**Comment by felixbrucker** [comment]
setting restart delay to 2sec (does this also affect normal mining?) results in a far better startup (97% cpu for 3 sec only after the first dag is copied)

setting dag mode to parallel results in far worse results, system was unusable

**Comment by felixbrucker** [comment]
setting restart delay to 2sec (does this also affect normal mining?) results in a far better startup (97% cpu for 3 sec only after the first dag is copied)

setting dag mode to parallel results in far worse results, system was unusable

**Comment by S74nk0** [comment]
`setting restart delay to 2sec (does this also affect normal mining?)` this affects all miner restarts when switching. What amount of RAM does this rig have more then 4GB?

**Comment by felixbrucker** [comment]
the rig has 8GB, miner just restarted (ethminer) and lagged again (significantly)

it only seems to occur on the first dag and shortly after

from the (garbled) text output it also seems the miner tries to start mining on gpu 0 though the dag is not copied yet

**Comment by S74nk0** [comment]
`it also seems the miner tries to start mining on gpu 0 though the dag is not copied yet` keep an eye on this. Does this issue occur only on this specific rig?

**Comment by felixbrucker** [comment]
i will monitor my other nvidia rig (1060s) if this also occurs there

**Comment by felixbrucker** [comment]
problem is mostly noticeable on some random restarts:

[2016-09-07 00:20:11] [INFO] [MinerEtherumCUDA] Pausing ethminer..
[2016-09-07 00:20:11] [INFO] [MinerEtherumCUDA] Resuming ethminer..

what could be the cause for this, or is this intentional?

**Comment by felixbrucker** [comment]
fyi original problem seems indeed just to be related to me noticing the rig being connected to both algos just after switching

**Comment by S74nk0** [comment]
`[2016-09-07 00:20:11] [INFO] [MinerEtherumCUDA] Pausing ethminer..
[2016-09-07 00:20:11] [INFO] [MinerEtherumCUDA] Resuming ethminer..` This is just a logging mistake and does not affect functionality (Thanks for pointing that out it will not log this anymore as it is misleading).

`fyi original problem seems indeed just to be related to me noticing the rig being connected to both algos just after switching` I am not sure what you meant to say here can you please elaborate? Does it mine on both miners at the same time?

**Comment by felixbrucker** [comment]
i currently have no screen of this but the miner definitely also paused and started again
(it showed something along the lines of "disconnecting farm" [...] "miner initializing [...]")

i meant to say i _think_ the original problem might be related to me looking at the web stats just at the time of switching between ethminer and lyra2rev2. i will continue to monitor this, but its sadly not reproducible

i noticed yet another ethminer related problem on my 1060s rig today:

ethminer hung from 1 am till i manually stopped and started the miner again at 5am and from 5:20 am till 9am

this is due network connectivity problems, but in previous versions of NHM it would detect the miner not outputing any hashes and restarting it after some timeout
why was this removed?
![unbenannt](https://cloud.githubusercontent.com/assets/5189997/18304920/6c4797fe-74e5-11e6-8133-c9bc21f607bb.PNG)

**Comment by S74nk0** [comment]
Hi @felixbrucker. Thanks for all the feedback. We will keep an eye on this potential issue. The restarting BUG should be fixed in the future release.

**Comment by S74nk0** [comment]
Hi @felixbrucker. Regarding ethminer and lyra2re double mining  problem. Have you had same issues on NiceHash Miner 1.6.1.4?

**Comment by felixbrucker** [comment]
on NHM 1.6.1.4 i could not mine eth as sm6.x support was still missing

with 1.6.1.4 everything else was working as expected though

**Comment by S74nk0** [comment]
Yes of course. We will be having a new release soon. We believe that most of these issues will be resolved. If not then of course report old/new issues. Thank you for your feedback! It has been very helpful.

**Comment by felixbrucker** [comment]
ok thanks, will try asap after i got the connectivity issues resolved with my provider

**Comment by felixbrucker** [comment]
small update: during the last 4 hours of testing none of the issues have appeared

will continue monitoring, but im confident
