### ISSUE TITLE
new version does not work for amd 

### ISSUE THREAD

**Issue by plifter** [nicehash/NiceHashMiner-Archived#269]
still crashing on all alogorithms  not sure how to get it working except to use a older version

**Comment by aaronsace** [comment]
All you can do is disable them all except ethereum on AMD. No idea why they have still not fixed this, I can manually run them in command line from the bin folder.

**Comment by S74nk0** [comment]
Hi all! We are having difficulties reproducing this issue on our AMD testing machines (they all work) and therefore we couldn't tell there are any issues. Of course we don't want to leave our AMD users hanging and we will fix this. I will post some patched versions on this thread and users that have this issue can report back if some of the patches fixes this (there were major code changes from 1.6 to 1.7), we would appreciate your feedback since we cannot reproduce this issue ourselves. In the mean time please test if the following works: 
- In the settings under **Devices/Algorithms** select a **sgminer** algorithm (any algorithm except ethereum/DaggerHashimoto) and set **Benchmark speed (H/s)** manually (any value bigger than 0).
- Disable **ethereum/DaggerHashimoto** for that AMD GPU.
- Save and Close settings and Start mining.

Please report if NHM will mine with sgminer, after these steps.

**Comment by plifter** [comment]
ok will try

**Comment by dakky221** [comment]
Tried what you said, tried Decred, Lyra2rev2, blake256r8vnl, X13 and Keccak and they all work if I input Benchmark speed manually. But Benchmark itself crashes the computer.

**Comment by S74nk0** [comment]
Hi all! Please try this [potential fix](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.0.0-dev/NiceHashMiner_v1.7.2.0_Potential_AMD_Fix.zip).

**Comment by dakky221** [comment]
Doesn't work potential fix.

**Comment by plifter** [comment]
seems like for me it was a voltage problem. when I fixed it. it started benchmarking

**Comment by technyne** [comment]
Still having issues with both of my AMD rigs using 1.7.3.3. Hashes fine if I manually put the rates in but when I try to benchmark it just skips over all of them and says its complete.  I tried the "possible fix" that was posted and it crashed my whole rig as soon as I started a benchmark.

**Comment by S74nk0** [comment]
Closing issue. All new questions regarding this issue should be discussed [here](https://github.com/nicehash/NiceHashMiner/issues/389) (#389).
