### ISSUE TITLE
v1.7.4.4 no settings are applied Claymore CryptoNight

### ISSUE THREAD

**Issue by bobiksamara** [nicehash/NiceHashMiner-Archived#589]
I set the parameter "-a 3" of mining during the "-a 4"

**Comment by S74nk0** [comment]
@bobiksamara there is a **BUG**. It will be fix.

**Comment by bobiksamara** [comment]
when corrected?

**Comment by cesarreynab** [comment]
Also Claymore Zcash is not reading custom parameters

**Comment by blue-yu** [comment]
Stanko, is that a reason why I am getting 260H/s cryptonight on 750ti with 1.7.4.4 versus 280H/s with 1.7.4.3?

**Comment by S74nk0** [comment]
@bobiksamara today.
@johiro What parameters aren't working? Our tests show that it does please give your case when it does not (open new issue).
@blue-yu yes lower hash-rate is due to incorrect parameter passing (fix coming soon)

**Comment by blue-yu** [comment]
@S74nk0 Hvala. Imas pivo od mene :+1:

**Comment by S74nk0** [comment]
[new version](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.5) is out. This issue is resolved.
Closing

**Comment by blue-yu** [comment]
Hm, there is still a problem with 750TI. 260h/s instead of 280h/s. I looks that --launch 8x40 is ignored even when I enter it manually. If I enter for example 8x39, than I got 8x40 for rest of cards. Also, it looks that "copy settings from" is not working :(

**Comment by S74nk0** [comment]
@blue-yu post the log to see if the parser isn't working or if the miner is correcting the input.

**Comment by blue-yu** [comment]
Here is the log:

> [2017-02-07 12:47:14] [INFO] [MiningSession] Current Global profit: 2.17387346 USD/Day
[2017-02-07 12:47:14] [INFO] [MiningSession] Current Global profit: IS PROFITABLE MinProfit mine always regardless of profit
[2017-02-07 12:47:14] [INFO] [ccminer_NVIDIA-MINER_ID(18)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
[2017-02-07 12:47:15] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "--launch=8x40" for device UUID GPU-ed012b4e-af28-2abd-b85d-ed61f6265d1b
[2017-02-07 12:47:15] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "--launch=8x40" for device UUID GPU-0a6282fb-e335-e4cf-aa57-0fd5be399d75
[2017-02-07 12:47:15] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "--launch=8x40" for device UUID GPU-7f7d38dd-e673-c239-0acd-e6997da15cf3
[2017-02-07 12:47:15] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "--launch=8x40" for device UUID GPU-6763948b-4d2c-27f9-18f7-43dbd282751a
[2017-02-07 12:47:15] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "--launch=8x40" for device UUID GPU-590d7a02-c790-2307-0d1a-ab4e689e55f8
[2017-02-07 12:47:15] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "--launch=8x40" for device UUID GPU-df62d5b6-7c28-4471-87a8-48ba14e430d2
[2017-02-07 12:47:15] [INFO] [ExtraLaunchParametersParser] Final extra launch params parse ""
[2017-02-07 12:47:15] [INFO] [ExtraLaunchParametersParser] DisableAMDTempControl is TRUE, temp control parameters will be ignored
[2017-02-07 12:47:15] [INFO] [ccminer_NVIDIA-MINER_ID(18)-DEVICE_IDs(0,1,2,3,4,5)] Starting miner [pid(3708)|bin(bin\ccminer_cryptonight.exe)]  --url=stratum+tcp://cryptonight.eu.nicehash.com:3355 --userpass=16yKPaWaEEbrpR1G8t1zxC4p9YcyViF1bV.rudar1:x  --devices  0,1,2,3,4,5
[2017-02-07 12:47:15] [INFO] [ccminer_NVIDIA-MINER_ID(18)-DEVICE_IDs(0,1,2,3,4,5)] [pid(3708)|bin(bin\ccminer_cryptonight.exe)] Starting cooldown checker
[2017-02-07 12:47:23] [INFO] [ccminer_NVIDIA-MINER_ID(18)-DEVICE_IDs(0,1,2,3,4,5)] [pid(3708)|bin(bin\ccminer_cryptonight.exe)] Shutting down miner
[2017-02-07 12:48:10] [INFO] [GroupSetupUtils] 
Disabled Devices:

And here is log from  miner:

> [2017-02-07 12:48:12] 6 miner threads started, using 'cryptonight' algorithm.
[2017-02-07 12:48:12] Binding thread 3 to cpu 3
[2017-02-07 12:48:12] GPU #3: GeForce GTX 750 Ti (5 SMX), using 20 blocks of 8 t
hreads
[2017-02-07 12:48:12] Binding thread 2 to cpu 2
[2017-02-07 12:48:12] GPU #2: GeForce GTX 750 Ti (5 SMX), using 20 blocks of 8 t
hreads
[2017-02-07 12:48:12] Binding thread 5 to cpu 5
[2017-02-07 12:48:12] GPU #5: GeForce GTX 750 Ti (5 SMX), using 20 blocks of 8 t
hreads
[2017-02-07 12:48:12] Binding thread 4 to cpu 4
[2017-02-07 12:48:12] GPU #4: GeForce GTX 750 Ti (5 SMX), using 20 blocks of 8 t
hreads
[2017-02-07 12:48:12] Pool set diff to 25000.1
[2017-02-07 12:48:12] Stratum detected new block
[2017-02-07 12:48:13] GPU #1: GeForce GTX 750 Ti, 126.48 H/s
[2017-02-07 12:48:13] GPU #5: GeForce GTX 750 Ti, 126.88 H/s
[2017-02-07 12:48:14] GPU #0: GeForce GTX 750 Ti, 81.46 H/s
[2017-02-07 12:48:18] GPU #3: GeForce GTX 750 Ti, 25.98 H/s
[2017-02-07 12:48:18] GPU #4: GeForce GTX 750 Ti, 25.96 H/s
[2017-02-07 12:48:18] GPU #2: GeForce GTX 750 Ti, 25.85 H/s

**Comment by S74nk0** [comment]
@blue-yu the reason for this is that `--launch=8x40` is the default and in the case of passing default values these are ignored (it is currently the way the parser works, for stability reasons). But this can be changed by the user now, if for example there are new miners and are copied over the bundled ones and the defaults are different there is an **internals** folder and this can be changed (more on this [here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#how-to-add-missing-miner-flag)). Now users can change/add new parameters and if you are concerned that the defaults aren't being passed just set the `"Default": "8x40"` to `"Default": ""`, this way the parser will not ignore the **Default** empty setting and it will pass. There were many complaints when people were changing miners (manually or by the updates) and the default values weren't being always up to date. Now with [this](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#how-to-add-missing-miner-flag) it is possible to make it working. I hope this helps. If the docs aren't clear let me know and we will improve it.

**Comment by S74nk0** [comment]
[MinerOptionPackage_ccminer_CryptoNight.zip](https://github.com/nicehash/NiceHashMiner/files/757520/MinerOptionPackage_ccminer_CryptoNight.zip)

@blue-yu if you copy this over to internals (unzipped) you should be good :). Let me know if it helps

**Comment by blue-yu** [comment]
Hi again,

Maybe I don't understand how thing are working, but I want 8x40 that is working faster for my 750ti's. In json file there is default set to 8x40, but NHM is not using it. Here are logs again, with default settings:

> [2017-02-07 18:46:09] [INFO] [MiningSession] Current Global profit: 2.11388743 USD/Day
[2017-02-07 18:46:09] [INFO] [MiningSession] Current Global profit: IS PROFITABLE MinProfit mine always regardless of profit
[2017-02-07 18:46:09] [INFO] [ccminer_NVIDIA-MINER_ID(30)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
[2017-02-07 18:46:10] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "" for device UUID GPU-ed012b4e-af28-2abd-b85d-ed61f6265d1b
[2017-02-07 18:46:10] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "" for device UUID GPU-0a6282fb-e335-e4cf-aa57-0fd5be399d75
[2017-02-07 18:46:10] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "" for device UUID GPU-7f7d38dd-e673-c239-0acd-e6997da15cf3
[2017-02-07 18:46:10] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "" for device UUID GPU-6763948b-4d2c-27f9-18f7-43dbd282751a
[2017-02-07 18:46:10] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "" for device UUID GPU-590d7a02-c790-2307-0d1a-ab4e689e55f8
[2017-02-07 18:46:10] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "" for device UUID GPU-df62d5b6-7c28-4471-87a8-48ba14e430d2
[2017-02-07 18:46:10] [INFO] [ExtraLaunchParametersParser] Final extra launch params parse ""
[2017-02-07 18:46:10] [INFO] [ExtraLaunchParametersParser] DisableAMDTempControl is TRUE, temp control parameters will be ignored
[2017-02-07 18:46:10] [INFO] [ccminer_NVIDIA-MINER_ID(30)-DEVICE_IDs(0,1,2,3,4,5)] Starting miner [pid(3416)|bin(bin\ccminer_cryptonight.exe)]  --url=stratum+tcp://cryptonight.eu.nicehash.com:3355 --userpass=16yKPaWaEEbrpR1G8t1zxC4p9YcyViF1bV.rudar1:x  --devices  0,1,2,3,4,5
[2017-02-07 18:46:10] [INFO] [ccminer_NVIDIA-MINER_ID(30)-DEVICE_IDs(0,1,2,3,4,5)] [pid(3416)|bin(bin\ccminer_cryptonight.exe)] Starting cooldown checker
[2017-02-07 18:46:20] [INFO] [NICEHASH] SMA get
[2017-02-07 18:46:47] [INFO] [ccminer_NVIDIA-MINER_ID(30)-DEVICE_IDs(0,1,2,3,4,5)] [pid(3416)|bin(bin\ccminer_cryptonight.exe)] Shutting down miner
[2017-02-07 18:48:20] [INFO] [NICEHASH] SMA get
[2017-02-07 18:50:04] [INFO] [NICEHASH] Balance get
[2017-02-07 18:50:20] [INFO] [NICEHASH] SMA get

But miner is doing:

>     *** ccminer-cryptonight 1.03 (32 bit) for nVidia GPUs by tsiv and KlausT
>     *** Built with Visual Studio 2013 using the Nvidia CUDA Toolkit 8.0
> 
>  tsiv's BTC donation address:   1JHDKp59t1RhHFXsTw2UQpR3F9BBz3R3cs
>  KlausT's BTC donation address: 1QHH2dibyYL5iyMDk3UN4PVvFVtrWD8QKp
>  for more donation addresses please read the README.txt
> -----------------------------------------------------------------
> [2017-02-07 18:46:10] Using JSON-RPC 2.0
> [2017-02-07 18:46:10] Binding thread 2 to cpu 2
> [2017-02-07 18:46:10] GPU #2: GeForce GTX 750 Ti (5 SMX), using 20 blocks of 8 t
> hreads
> [2017-02-07 18:46:10] 6 miner threads started, using 'cryptonight' algorithm.
> [2017-02-07 18:46:10] Starting Stratum on stratum+tcp://cryptonight.eu.nicehash.
> com:3355
> [2017-02-07 18:46:10] Binding thread 1 to cpu 1
> [2017-02-07 18:46:10] GPU #1: GeForce GTX 750 Ti (5 SMX), using 20 blocks of 8 t
> hreads
> [2017-02-07 18:46:10] Binding thread 4 to cpu 4
> [2017-02-07 18:46:10] GPU #4: GeForce GTX 750 Ti (5 SMX), using 20 blocks of 8 t
> hreads
> [2017-02-07 18:46:10] Binding thread 3 to cpu 3
> [2017-02-07 18:46:10] GPU #3: GeForce GTX 750 Ti (5 SMX), using 20 blocks of 8 t
> hreads
> [2017-02-07 18:46:10] Binding thread 5 to cpu 5
> [2017-02-07 18:46:10] GPU #5: GeForce GTX 750 Ti (5 SMX), using 20 blocks of 8 t
> hreads
> [2017-02-07 18:46:10] Binding thread 0 to cpu 0
> [2017-02-07 18:46:10] GPU #0: GeForce GTX 750 Ti (5 SMX), using 20 blocks of 8 t
> hreads
> [2017-02-07 18:46:11] Pool set diff to 25000.1
> [2017-02-07 18:46:11] Stratum detected new block
> [2017-02-07 18:46:12] GPU #1: GeForce GTX 750 Ti, 136.39 H/s
> [2017-02-07 18:46:12] GPU #2: GeForce GTX 750 Ti, 136.05 H/s
> [2017-02-07 18:46:12] GPU #3: GeForce GTX 750 Ti, 135.13 H/s
> [2017-02-07 18:46:12] GPU #5: GeForce GTX 750 Ti, 135.13 H/s
> [2017-02-07 18:46:12] GPU #0: GeForce GTX 750 Ti, 134.90 H/s
> [2017-02-07 18:46:12] GPU #4: GeForce GTX 750 Ti, 131.90 H/s
> [2017-02-07 18:46:13] GPU #5: GeForce GTX 750 Ti, 247.47 H/s
> [2017-02-07 18:46:13] accepted: 1/1 (100.00%), 921.84 H/s (yay!!!)
> 
> 

So, You see that with the default it should be 8x40, but it is doing 8x20...

**Comment by blue-yu** [comment]
Again I must say that with 1.7.4.3 default is 8x40 and with 1.7.4.4 and 1.7.4.5 default is lowered to 8x20

**Comment by S74nk0** [comment]
@blue-yu yes that is because the default parameters aren't up to date. In the NiceHash Miner folder there is a folder named **internals** in that folder there are supported **MinerOptionPackages** in this case we are interested at **MinerOptionPackage_ccminer_CryptoNight.json** file. The default Launch in that file is set to **8x40** and this is not correct anymore it should be **8x20**. To fix this one can edit the **Launch** option to change the **Default** value. This file [MinerOptionPackage_ccminer_CryptoNight.zip](https://github.com/nicehash/NiceHashMiner/files/758555/MinerOptionPackage_ccminer_CryptoNight.zip) has the **Default** set to **8x20**, and when you copy it over the original **8x40** will get accepted by the parser. 

So to fix this issue you only have to copy over the **MinerOptionPackage_ccminer_CryptoNight.json** in the zip file provided here over the current **MinerOptionPackage_ccminer_CryptoNight.json** in the **internals** folder. Make sure NHM is closed when doing this. After the next run of NHM the **8x40** will not be ignored. That will resolve the issue. The defaults have been corrected for future versions, but there is no need to wait for a new release. Just copy the file and it should work. Let me know if it helps.

**Comment by blue-yu** [comment]
Aaaa, ok I understand now. I copied json file, and then manually enter -l 8x40 parameter for all of my cards. It's working now. I Just don't understand why did You change from 8x40 to 8x20 since 8x40 is working faster for 750ti

**Comment by boby361** [comment]
Not sure if its still a bug. I have gone to cryptonight claymore_old folder. altered the bat and added -a 3 to the end of it. I have gone to the interals folder. edited MinerOptionPackage_ClaymoreCryptoNight.json (assuming it shares config with old) and altered the default to 3. still opens with 4. not sure what else to do. But it seems like this bug still exists.
