### ISSUE TITLE
infinite error dialogs when started without internet

### ISSUE THREAD

**Issue by CreamyG31337** [nicehash/NiceHashMiner-Archived#6]
I noticed on computers with wifi if the wifi is not connected we get an error dialog saying that the profitability data cannot be retrieved. This repeats every second or so until the application exhausts the computer's resources.

**Comment by kenshirothefist** [comment]
Fixed in 1.2.0.2

**Comment by CreamyG31337** [comment]
this isn't really fixed, now it pops up 'check internet connection' dialogs in a stack...

**Comment by theLosers106** [comment]
If you are using the latest version of NiceHashMiner then it should be fixed. Proof: https://github.com/nicehash/NiceHashMiner/blob/master/NiceHashMiner/Form1.cs#L549

If you press Yes when the dialog pops up, then it will set ShowWarningNiceHashData  to false (https://github.com/nicehash/NiceHashMiner/blob/master/NiceHashMiner/Form1.cs#L560) and therefore it won't go into that if anymore.. if you choose No then it will just exit NiceHashMiner.

**Comment by CreamyG31337** [comment]
![nicehash](https://cloud.githubusercontent.com/assets/11222932/13678052/faec2de6-e6a9-11e5-8799-3026e80298eb.png)

by the time i connect and authenticate my wifi, i have a huge stack like this.

**Comment by theLosers106** [comment]
Will be fixed in the next release..

**Comment by theLosers106** [comment]
This issue has been addressed in the latest Release 1.3.0.1
https://github.com/nicehash/NiceHashMiner/releases/tag/1.3.0.1
