### ISSUE TITLE
NiceHash 1.7.5.1 It does not start automatically (warning of virtual memory)

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/NiceHashMiner-Archived#667]
NiceHash 1.7.5.1 It does not start automatically (warning of virtual memory). 
On some farms it is not physically possible to increase the size of the swap file - SDD 64Gbyte, Win 7 operating system ballooned to a maximum.

Make the ability to disable warning. Thank you in advance!

**Comment by fefsf** [comment]
With the X11GOST miner, you will run into memory problems unless your VM is adjusted to at least 24GB (8GB RAM, 6 GPU rig, less VM needed for lesser GPUs). This is probably why they incorporated the warning. 

Even with a 64GB SSD, you should still have space for a 24GB swap file, considering its already taking up several GB.

**Comment by S74nk0** [comment]
[Fixed](https://github.com/nicehash/NiceHashMiner/commit/8dc28dcd646724ae77ad7d1fc960788ae0fc165d) and will be available in the next release... Closing

**Comment by 619Srt** [comment]
Yeah still not fixed. LOL in how long now. I am seriously considering going to another miner because of all these issues and nobody i can find to help me with fixing them
