### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by AMDfreak** [nicehash/NiceHashMiner-Archived#997]
Just started the miner again and getting this for the CPU side:

[2017-06-09 01:26:43] : Connecting to pool cryptonight.usa.nicehash.com:3355 ...
[2017-06-09 01:26:43] : SOCKET ERROR - CONNECT error: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by haircl0ne** [comment]
I also get connection error. Been trying to solve it for days now... How come I can only choose to connect to cryptoNight?

![capture](https://user-images.githubusercontent.com/29460862/27189712-7c117a5c-51f2-11e7-84c4-ad8ecb24bbc0.PNG)

**Comment by miladebram** [comment]
yeh . I also have this problem . No one to help me

**Comment by Alphaweblabs** [comment]
There's one solution, 
You need to uninstall Nicehash miner then restart your system. 
next reinstall the miner and then change the region and start mining.  here you go, this should solve the issue.

**Comment by miladebram** [comment]
excellent . Thank you
But my problem was not resolved. 
It works fine at first, but after 10 minutes, the error will appear. 
Virtual Memory Size, that should fix it:

"Computer Properties / Advanced System Settings / Performance / Advanced / Virtual Memory" (Put it too 16gb).    
I also did this, but the problem did not resolve and still renders it . :(

**Comment by CrizzzSombiii** [comment]
Same Problem.

**Comment by Alphaweblabs** [comment]
Try changing the region and this will also solve the error. Nice hash
doesn't have back up pool that is the reason it is giving error for
cryptonite algorithm.
